# coding: utf-8

"""
    Data Integration API

    Easily and directly query database backup files, convert into other file formats.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dataintegration_api_client
from cloudmersive_dataintegration_api_client.models.mssql_table import MssqlTable  # noqa: E501
from cloudmersive_dataintegration_api_client.rest import ApiException


class TestMssqlTable(unittest.TestCase):
    """MssqlTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMssqlTable(self):
        """Test MssqlTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_dataintegration_api_client.models.mssql_table.MssqlTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
