# coding: utf-8

"""
    videoapi

    The video APIs help you convert, encode, and transcode videos.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dataintegration_api_client
from cloudmersive_dataintegration_api_client.api.video_api import VideoApi  # noqa: E501
from cloudmersive_dataintegration_api_client.rest import ApiException


class TestVideoApi(unittest.TestCase):
    """VideoApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_dataintegration_api_client.api.video_api.VideoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_video_convert_to_gif(self):
        """Test case for video_convert_to_gif

        Convert Video to Animated GIF format.  # noqa: E501
        """
        pass

    def test_video_convert_to_mov(self):
        """Test case for video_convert_to_mov

        Convert Video to MOV format.  # noqa: E501
        """
        pass

    def test_video_convert_to_mp4(self):
        """Test case for video_convert_to_mp4

        Convert Video to MP4 format.  # noqa: E501
        """
        pass

    def test_video_convert_to_still_frames(self):
        """Test case for video_convert_to_still_frames

        Convert Video to PNG Still Frames.  # noqa: E501
        """
        pass

    def test_video_convert_to_webm(self):
        """Test case for video_convert_to_webm

        Convert Video to WEBM format.  # noqa: E501
        """
        pass

    def test_video_cut_video(self):
        """Test case for video_cut_video

        Cut a Video to a Shorter Length  # noqa: E501
        """
        pass

    def test_video_get_info(self):
        """Test case for video_get_info

        Get detailed information about a video or audio file  # noqa: E501
        """
        pass

    def test_video_resize_video(self):
        """Test case for video_resize_video

        Resizes a Video Preserving the Original Aspect Ratio.  # noqa: E501
        """
        pass

    def test_video_resize_video_simple(self):
        """Test case for video_resize_video_simple

        Resizes a Video without Preserving Aspect Ratio.  # noqa: E501
        """
        pass

    def test_video_scan_for_nsfw(self):
        """Test case for video_scan_for_nsfw

        Scan a Video for NSFW content.  # noqa: E501
        """
        pass

    def test_video_split_video(self):
        """Test case for video_split_video

        Split a Video into Two Shorter Videos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
