# coding: utf-8

"""
    Data Integration API

    Easily and directly query database backup files, convert into other file formats.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dataintegration_api_client
from cloudmersive_dataintegration_api_client.api.backup_convert_api import BackupConvertApi  # noqa: E501
from cloudmersive_dataintegration_api_client.rest import ApiException


class TestBackupConvertApi(unittest.TestCase):
    """BackupConvertApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_dataintegration_api_client.api.backup_convert_api.BackupConvertApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dataintegration_backup_convert_mssql_bak_get_tables_post(self):
        """Test case for dataintegration_backup_convert_mssql_bak_get_tables_post

        Lists all tables stored in a SQL Server Backup (.BAK) file  # noqa: E501
        """
        pass

    def test_dataintegration_backup_convert_mssql_bak_to_csv_post(self):
        """Test case for dataintegration_backup_convert_mssql_bak_to_csv_post

        Converts a SQL Server Backup (.BAK) file into CSV for a specified table  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
