# coding: utf-8

"""
    videoapi

    The video APIs help you convert, encode, and transcode videos.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dataintegration_api_client
from cloudmersive_dataintegration_api_client.models.still_frame import StillFrame  # noqa: E501
from cloudmersive_dataintegration_api_client.rest import ApiException


class TestStillFrame(unittest.TestCase):
    """StillFrame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStillFrame(self):
        """Test StillFrame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_dataintegration_api_client.models.still_frame.StillFrame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
