# coding: utf-8

"""
    videoapi

    The video APIs help you convert, encode, and transcode videos.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_dataintegration_api_client
from cloudmersive_dataintegration_api_client.models.nsfw_scanned_frame import NsfwScannedFrame  # noqa: E501
from cloudmersive_dataintegration_api_client.rest import ApiException


class TestNsfwScannedFrame(unittest.TestCase):
    """NsfwScannedFrame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNsfwScannedFrame(self):
        """Test NsfwScannedFrame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_dataintegration_api_client.models.nsfw_scanned_frame.NsfwScannedFrame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
